language: node_js
node_js:
  - latest
dist: trusty
services:
  - mongodb
env:
  - PORT=3000 NODE_ENV=production
cache:
  directories:
    - node_module
install:
  - npm install
script:
  - nohup npm start &
  - sleep 3
  - npm run test
