language: node_js
node_js:
  - 10
dist: trusty
services:
  - mongodb
cache:
  directories:
    - node_module
install:
  - npm install
script:
  - nohup npm run start:ci &
  - sleep 3
  - npm run test:ci
