#%RAML 1.0
baseUri: http://localhost:3000
title: Customer APIs

/api:
  /customers:
    # GET api/customer
    get:
      description: 'get all customers'
      responses:
        200:
          description: "return 200 and existing users"
          body:
            application/json:
              example: {
                "customers":"to be sent to client"
              }
        500:
          description: "return 500 if something internally happened"
          body:
            application/json:
              example: {
                "error": "internal server error"
              }

    /signup:
      # POST api/customer/signup
      post:
        description: 'post a new customer'
        body:
          application/json:
            example: {
              "customer": "data to be sent"
            }
        responses:
          400:
            description: "return 400 if user is already exist or invalid data are passed"
            body:
              application/json:
                example: {
                  "customer": "user already exist or invalid data are passed"
                }
          200:
            description: "return 200 if user has been saved"
            body:
              application/json:
                example: {
                  "customer": "has been successfully saved"
                }
          500:
            description: "return 500 if something internally happened"
            body:
              application/json:
                example: {
                  "error": "internal server error"
                }

    /signin:
      # POST api/customer/signin
      post:
        description: 'signing in a customer'
        body:
          application/json:
            example: {
              "customer": "data to be sent"
            }
        responses:
          400:
            body:
              application/json:
                example: {
                  "customer": "return 400 if invalid data are passed"
                }
          404:
            body:
              application/json:
                example: {
                  "customer": "return 404 if the user is not found"
                }
          200:
            body:
              application/json:
                example: {
                  "customer": "has been successfully saved"
                }
          500:
            body:
              application/json:
                example: {
                  "error": "internal server error"
                }

    /update:
      # PUT api/customer
      put:
        description: "update customer data"
        body:
          application/json:
            example: {
              "data": "to update"
            }
        responses:
          401:
            description: "return 401 if user is not logged in"
            body:
              application/json:
                example: {
                  "message": "you have to login"
                }
          403:
            description: "return 403 if user do not have the permission to delete"
            body:
              application/json:
                example: {
                  "message": "you do not have a permission"
                }
          404:
            description: "return 404 if the user not found"
            body:
              application/json:
                example: {
                  "message": "user not found"
                }
          200:
            description: "return 200 if the user is successfully updated"
            body:
              application/json:
                example: {
                  "message": "user has been updated successfully"
                }

    /delete:
      # DELETE api/customer
      delete:
        description: "delete a customer"
        queryParameters:
          id:
        responses:
          401:
            description: "return 401 if user is not logged in"
            body:
              application/json:
                example: {
                  "message": "you have to login"
                }
          403:
            description: "return 403 if user do not have the permission to delete"
            body:
              application/json:
                example: {
                  "message": "you do not have a permission"
                }
          404:
            description: "user not found"
            body:
              application/json:
                example: {
                  "message": "user not found"
                }
          200:
            description: "successfully deleted"
            body:
              application/json:
                example: {
                  "message": "user has been deleted successfully"
                }

    /{id}:
      # GET api/customer/id
      get:
        description: "get one customer"
        responses:
          401:
            description: "return 401 if the user is not logged in"
            body:
              application/json:
                example: {
                  "message": "you have to login"
                }
          404:
            description: "return 404 if user is not found"
            body:
              application/json:
                example: {
                  "message": "user not found"
                }
          200:
            description: "return 200 if user is found"
            body:
              application/json:
                example: {
                  "customer": "returned from db"
                }
